# sqlite3 and postgresql configurations:

development:
  adapter: postgresql
  encoding: unicode
  database: service_development
  pool: 5
  username: oleh
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: service_test
  pool: 5psql
  username: oleh
  password:
